version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: safevault-postgres
    environment:
      POSTGRES_USER: safevaultuser
      POSTGRES_PASSWORD: daanisthebest
      POSTGRES_DB: safevaultdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
